# Juego ejemplo 7
j <- 2
pe_j1 <- c('a', 'b')
pe_j2 <- c('A', 'B', 'C')
filas <- length(pe_j1)*length(pe_j2)
juego_ej7 <- data.frame(matrix(NA, nrow = filas, ncol = j*2), stringsAsFactors=FALSE)
names(juego_ej7) <- c('S1', 'S2', 'PHI1', 'PHI2')
juego_ej7[1,] <- c('a', 'A', 3, 6)
juego_ej7[2,] <- c('a', 'B', 5, 2)
juego_ej7[3,] <- c('a', 'C', 4, 1)
juego_ej7[4,] <- c('a', 'D', 7, 1)
juego_ej7[5,] <- c('b', 'A', 1, 7)
juego_ej7[6,] <- c('b', 'B', 1, 3)
juego_ej7[7,] <- c('b', 'C', 5, 2)
juego_ej7[8,] <- c('b', 'D', 4, 2)
juego_ej7[9,] <- c('c', 'A', 0, 8)
juego_ej7[10,] <- c('c', 'B', 4, 1)
juego_ej7[11,] <- c('c', 'C', 5, -1)
juego_ej7[12,] <- c('c', 'D', 1, -1)